$dna='CTACTCAGCCCCAGCGGAGGTGAAGGTTTTTCGTCCTTCCCCAGGAGCCGGTGAGAAGCGCAGTCGGGGGCACGGGGATGAGCTCAGGGGCCTCTAGAAAGAGCTGGGACCCTGGGAACCCCTGGCCTCCAGGTAGTCTCAGGAGAGCTACTCGGGGTCGGGCTTGGGGAGAGGAGGAGCGGGGGTGAGGCAAGCAGCAGGGGACTGGACCTGGGAAGGGCTGGGCAGCAGAGACGACCCGACCCGCTAGAAGGTGGGGTAGAGTTTTTTTCAGCTGGACTGGGATGTAAGCCATAGCAGGACTCCACGAGTTGTCACTATCATTTATCGAGCACCTACTGGGTGTCCCCAGTGTCCTCAGATCTCCATAACTGGGGAGCCAGGGGCAGCGACACGGTAGCTAGCCGTCGATTGGAGAACTTTAAAA';
$dna=~ s/\s//g;

$countA=($dna=~tr/Aa//);
$countC=($dna=~tr/Cc//);
$countG=($dna=~tr/Gg//);
$countT=($dna=~tr/Tt//);

print "C=$countC G=$countG"; 
$p=$countA+$countC+$countG+$countT ;

print "\nprecentag of 'G'";
$pc=int(($countG/$p)*100);

print  "\n$pc%";
print  "\npercentage of 'C'";
$pc=int(($countC/$p)*100);
print "\n$pc%";
